name: diario_el_pueblo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  salomon_bottom_bar: ^3.3.2
  font_awesome_flutter: ^10.5.0
  url_launcher: ^6.1.12
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  timezone: ^0.9.2
  http: ^1.1.0
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  cached_memory_image: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/