name: diario_el_pueblo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  salomon_bottom_bar: ^3.3.2
  font_awesome_flutter: ^10.5.0
  url_launcher: ^6.1.12
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  timezone: ^0.9.2
  http: ^1.1.0
  shimmer: ^3.0.0
  cached_network_image: ^3.2.3
  cached_memory_image: ^1.3.1
  flutter_html: ^3.0.0-alpha.3
  syncfusion_flutter_pdfviewer: ^22.2.7
  path_provider: ^2.0.15
  encrypt: ^5.0.1
  path: ^1.8.3
  lottie: ^2.5.0
  flutter_native_splash: ^2.3.1

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#FFFFFF"
  image: "assets/external/splash_image.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/external/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Light.otf
        - asset: fonts/Poppins-Regular.otf
        - asset: fonts/Poppins-SemiBold.otf
        - asset: fonts/Poppins-Medium.otf
        - asset: fonts/Poppins-Bold.otf
          weight: 700
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf